-- UC-001: identity resolution needs employees and departments; login attempts are audited.
-- Portable SQL: runs unchanged on PostgreSQL (production) and H2 (tests, dev profile).

CREATE TABLE department (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE employee (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320)             NOT NULL,
    first_name    VARCHAR(255)             NOT NULL,
    last_name     VARCHAR(255)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,
    manager_id    BIGINT,
    department_id BIGINT                   NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE     NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT ck_employee_role CHECK (role IN ('EMPLOYEE', 'MANAGER', 'ADMIN')),
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES employee (id),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE INDEX idx_employee_manager ON employee (manager_id);
CREATE INDEX idx_employee_department ON employee (department_id);

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id     BIGINT,
    entity_type VARCHAR(100)             NOT NULL,
    entity_id   BIGINT,
    action      VARCHAR(30)              NOT NULL,
    old_values  VARCHAR(4000),
    new_values  VARCHAR(4000),
    reason      VARCHAR(1000),
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES employee (id)
);

CREATE INDEX idx_audit_log_occurred_at ON audit_log (occurred_at);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
