-- UC-002: work periods (check-in to check-out) as absolute UTC instants.
-- Portable SQL: runs unchanged on PostgreSQL (production) and H2 (tests, dev profile).

CREATE TABLE time_entry (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT                   NOT NULL,
    check_in_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    check_out_at     TIMESTAMP WITH TIME ZONE,
    -- Equals employee_id while the period is open, otherwise NULL. The unique constraint guarantees at
    -- most one open period per employee even with concurrent sessions or application instances
    -- (NULLs never collide, so any number of completed periods is fine).
    open_employee_id BIGINT,
    version          BIGINT                   NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_time_entry_employee FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT uq_time_entry_open_employee UNIQUE (open_employee_id),
    CONSTRAINT ck_time_entry_period CHECK (check_out_at IS NULL OR check_out_at >= check_in_at),
    CONSTRAINT ck_time_entry_open CHECK (
        (check_out_at IS NULL AND open_employee_id = employee_id)
        OR (check_out_at IS NOT NULL AND open_employee_id IS NULL))
);

CREATE INDEX idx_time_entry_employee_check_in ON time_entry (employee_id, check_in_at);
