-- UC-004: whether a work period may still be corrected depends on the status of the monthly timesheet.
-- A timesheet only exists once it was created (UC-005) and defaults to DRAFT until then; submission,
-- approval and rejection details are added by the use cases that need them.
-- Portable SQL: runs unchanged on PostgreSQL (production) and H2 (tests, dev profile).

CREATE TABLE timesheet (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT                   NOT NULL,
    period_year  INTEGER                  NOT NULL,
    period_month INTEGER                  NOT NULL,
    status       VARCHAR(20)              NOT NULL,
    version      BIGINT                   NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_timesheet_employee FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT uq_timesheet_employee_period UNIQUE (employee_id, period_year, period_month),
    CONSTRAINT ck_timesheet_month CHECK (period_month BETWEEN 1 AND 12),
    CONSTRAINT ck_timesheet_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_timesheet_status ON timesheet (status);
