-- UC-005: the monthly timesheet shows who approved or rejected it and why, and marks public holidays.
-- The approval columns are filled by the submission and approval use cases (UC-006, UC-007); public holidays
-- are managed by UC-012. Portable SQL: runs unchanged on PostgreSQL and H2.

ALTER TABLE timesheet ADD COLUMN submitted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE timesheet ADD COLUMN approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE timesheet ADD COLUMN approved_by BIGINT;
ALTER TABLE timesheet ADD COLUMN rejected_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE timesheet ADD COLUMN rejected_by BIGINT;
ALTER TABLE timesheet ADD COLUMN rejection_reason VARCHAR(1000);
ALTER TABLE timesheet ADD CONSTRAINT fk_timesheet_approved_by FOREIGN KEY (approved_by) REFERENCES employee (id);
ALTER TABLE timesheet ADD CONSTRAINT fk_timesheet_rejected_by FOREIGN KEY (rejected_by) REFERENCES employee (id);

CREATE TABLE public_holiday (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE                     NOT NULL,
    name         VARCHAR(255)             NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_public_holiday_date UNIQUE (holiday_date)
);
