-- UC-017: public holidays per region. Regions are kept by the administrator; every employee has one region and
-- every holiday belongs to one region. Existing employees and holidays go to the region "Default", which is the
-- first row of the table (id 1) and can be renamed. The date of a holiday is unique per region, not any more for the
-- whole company. Portable SQL: runs unchanged on PostgreSQL and H2.

CREATE TABLE region (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)             NOT NULL,
    version    BIGINT                   NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_region_name UNIQUE (name)
);

INSERT INTO region (name, version, created_at, updated_at)
VALUES ('Default', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE employee ADD COLUMN region_id BIGINT;
UPDATE employee SET region_id = (SELECT id FROM region WHERE name = 'Default');
ALTER TABLE employee ALTER COLUMN region_id SET NOT NULL;
ALTER TABLE employee ADD CONSTRAINT fk_employee_region FOREIGN KEY (region_id) REFERENCES region (id);
CREATE INDEX idx_employee_region ON employee (region_id);

ALTER TABLE public_holiday ADD COLUMN region_id BIGINT;
UPDATE public_holiday SET region_id = (SELECT id FROM region WHERE name = 'Default');
ALTER TABLE public_holiday ALTER COLUMN region_id SET NOT NULL;
ALTER TABLE public_holiday ADD CONSTRAINT fk_public_holiday_region FOREIGN KEY (region_id) REFERENCES region (id);
ALTER TABLE public_holiday DROP CONSTRAINT uq_public_holiday_date;
ALTER TABLE public_holiday ADD CONSTRAINT uq_public_holiday_region_date UNIQUE (region_id, holiday_date);
